package com.auth0.android.provider;

import com.auth0.android.authentication.AuthenticationException;
import com.auth0.android.callback.RunnableTask;
import kotlin.Metadata;

@Metadata(d1 = {"\u0000\f\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\b\n\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001Â¨\u0006\u0003"}, d2 = {"com/auth0/android/provider/AuthenticationActivity$launchAuthenticationIntent$1", "Lcom/auth0/android/callback/RunnableTask;", "Lcom/auth0/android/authentication/AuthenticationException;", "auth0_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
/* loaded from: classes.dex */
public final class AuthenticationActivity$launchAuthenticationIntent$1 implements RunnableTask<AuthenticationException> {

    /* renamed from: a, reason: collision with root package name */
    public final /* synthetic */ AuthenticationActivity f13660a;

    public AuthenticationActivity$launchAuthenticationIntent$1(AuthenticationActivity authenticationActivity) {
        this.f13660a = authenticationActivity;
    }
}
